AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 10
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-test-retoruto-carry/ec4258a1ec10aabfe8d9d872b5105ade
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(1 1,11,15 * * ? *)
      Environment:
        Variables:
          TZ: Asia/Tokyo
          TWITTER_CONSUMER_KEY: twitterConsumerKey
          TWITTER_CONSUMER_SECRET: twitterConsumerSecret
          TWITTER_ACCESS_TOKEN_KEY: twitterAccessTokenKey
          TWITTER_ACCESS_TOKEN_SECRET: twiiterAccessTokenSecret
