AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "\u6708\u306E\u4F55\u5272\u304C\u7D4C\u904E\u3057\u3066\u3044\u308B\u304B\
  \u3092\u3064\u3076\u3084\u304FtwitterBot"
Globals:
  Function:
    Timeout: 10
Resources:
  MonthProgressTwitterBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://month-progress-twitter-bot/ec4258a1ec10aabfe8d9d872b5105ade
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(1 1,11,15 * * ? *)
      Environment:
        Variables:
          TZ: Asia/Tokyo
          TWITTER_CONSUMER_KEY: twitterConsumerKey
          TWITTER_CONSUMER_SECRET: twitterConsumerSecret
          TWITTER_ACCESS_TOKEN_KEY: twitterAccessTokenKey
          TWITTER_ACCESS_TOKEN_SECRET: twiiterAccessTokenSecret
