AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 月の何割が経過しているかをつぶやくtwitterBot
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10


Resources:

    ScheduledFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: src/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Events:
                ScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: cron(1 1,11,15 * * ? *) #UTCなのでJSTに合わせるために-9時間
            Environment:
                Variables:
                    TZ: Asia/Tokyo
                    TWITTER_CONSUMER_KEY: twitterConsumerKey
                    TWITTER_CONSUMER_SECRET: twitterConsumerSecret
                    TWITTER_ACCESS_TOKEN_KEY: twitterAccessTokenKey
                    TWITTER_ACCESS_TOKEN_SECRET: twiiterAccessTokenSecret